version: "3.7"

services:
  vaultwarden:
    image: vaultwarden/server:latest
    volumes:
      - /opt/vaultwarden/data:/data
    ports:
      - "80"
    environment:
      WEBSOCKET_ENABLED: "true"
