version: "3"

services:
  bitwarden:
    image: vaultwarden/server:latest
    container_name: bitwarden
    ports:
      - "8081:80"
    volumes:
      - bitwarden-data:/data
    environment:
      - DOMAIN=http://10.16.63.50:8081   # ✅ 반드시 명시
    restart: unless-stopped
