version: "3"

services:
  bitwarden:
    image: vaultwarden/server:latest
    container_name: bitwarden
    ports:
      - "8081:80"
    volumes:
      - bitwarden-data:/data
    restart: unless-stopped

volumes:
  bitwarden-data:
